"""Generate references.bib from a project's catalog.json.

Usage:
    python tools/build_bib.py --project projects/<slug> \
        --out projects/<slug>/references.bib

    # Limit to keys cited in a Pandoc-style draft:
    python tools/build_bib.py --project projects/<slug> \
        --only-cited projects/<slug>/lit-review.md \
        --out projects/<slug>/references.bib
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _common import read_json

PANDOC_CITE_RE = re.compile(r"\[@([a-z0-9]+(?:[;,\s]+@[a-z0-9]+)*)\]")
SINGLE_KEY_RE = re.compile(r"@([a-z0-9]+)")


def _entry_type(catalog_entry: dict) -> str:
    venue = (catalog_entry.get("venue") or "").lower()
    if catalog_entry.get("arxiv_id") and "arxiv" in venue or venue == "":
        if catalog_entry.get("arxiv_id"):
            return "misc"
    if any(k in venue for k in ("journal", "transactions", "letters", "review")):
        return "article"
    if any(k in venue for k in ("conference", "proceedings", "workshop", "symposium")):
        return "inproceedings"
    if "book" in venue:
        return "book"
    if not venue:
        return "misc"
    return "article"


def _escape_bib(value: str) -> str:
    if value is None:
        return ""
    # Minimal escaping: protect special LaTeX characters and wrap braces around
    # words with internal uppercase to preserve casing in the bibliography.
    text = (
        value.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )
    return text


def _format_authors(authors: list[str]) -> str:
    return " and ".join(_escape_bib(a) for a in authors if a)


def render_entry(e: dict) -> str:
    etype = _entry_type(e)
    fields: list[tuple[str, str]] = []
    if e.get("title"):
        fields.append(("title", "{" + _escape_bib(e["title"]) + "}"))
    if e.get("authors"):
        fields.append(("author", _format_authors(e["authors"])))
    if e.get("year") is not None:
        fields.append(("year", str(e["year"])))
    venue = e.get("venue")
    if venue and etype != "misc":
        venue_field = "booktitle" if etype == "inproceedings" else "journal"
        fields.append((venue_field, _escape_bib(venue)))
    if e.get("doi"):
        fields.append(("doi", e["doi"]))
    if e.get("url"):
        fields.append(("url", e["url"]))
    if e.get("arxiv_id"):
        fields.append(("eprint", e["arxiv_id"]))
        fields.append(("archivePrefix", "arXiv"))
    if etype == "misc" and e.get("arxiv_id"):
        fields.append(("note", f"arXiv:{e['arxiv_id']}"))

    body = ",\n  ".join(f"{k} = {{{v}}}" if not (v.startswith("{") and v.endswith("}")) else f"{k} = {v}"
                       for k, v in fields)
    return f"@{etype}{{{e['key']},\n  {body}\n}}\n"


def cited_keys(draft_path: Path) -> set[str]:
    text = draft_path.read_text(encoding="utf-8")
    keys: set[str] = set()
    for m in PANDOC_CITE_RE.finditer(text):
        for k in SINGLE_KEY_RE.findall("@" + m.group(1)):
            keys.add(k)
    # Also catch bare `@key` outside brackets, which Pandoc supports.
    for m in re.finditer(r"(?<![\w@])@([a-z0-9]+)", text):
        keys.add(m.group(1))
    return keys


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render BibTeX from catalog.json.")
    p.add_argument("--project", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--only-cited", help="Markdown draft path; emit only keys cited within it.")
    args = p.parse_args(argv)

    proj = Path(args.project)
    catalog = read_json(proj / "catalog.json")
    entries = catalog.get("entries", [])

    if args.only_cited:
        draft = Path(args.only_cited)
        if not draft.exists():
            sys.stderr.write(f"Draft not found: {draft}\n")
            return 1
        wanted = cited_keys(draft)
        catalog_keys = {e.get("key") for e in entries}
        missing = wanted - catalog_keys
        if missing:
            sys.stderr.write(
                f"ERROR: draft cites keys not in catalog: {sorted(missing)}\n"
                "Add the entries (tools/catalog.py add) or remove the citations.\n"
            )
            return 1
        entries = [e for e in entries if e.get("key") in wanted]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(f"% Generated by tools/build_bib.py from {proj / 'catalog.json'}\n")
        fh.write(f"% {len(entries)} entries.\n\n")
        for e in entries:
            if not e.get("key"):
                continue
            fh.write(render_entry(e))
            fh.write("\n")
    sys.stderr.write(f"Wrote {len(entries)} BibTeX entries to {out}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
